# Generated by Django 4.2.7 on 2023-11-15 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 1, 39, 49, 253821, tzinfo=datetime.timezone.utc)),
        ),
    ]
